"""
TESTS is a dict with all of your tests.
Keys for this will be the categories' names.
Each test is a dict with
    "input" -- input data for a user function
    "answer" -- your right answer
    "explanation" -- not necessarily a key, it's used for an additional info in animation.
"""


TESTS = {
    "Basics": [
        {
            "input": [["abab", "baba", ""]],
            "answer": 7,
            "explanation": [
                ['abab', 'baba', ''], 
                ['bab', 'baba', 'a'], 
                ['bbab', 'aba', 'a'], 
                ['bbab', 'ba', 'aa'], 
                ['ab', 'bbba', 'aa'], 
                ['b', 'bbba', 'aaa'], 
                ['bbbb', 'a', 'aaa'], 
                ['bbbb', '', 'aaaa']],
        },
        {
            "input": [["abcc", "abca", "bcab", "", ""]],
            "answer": 10,
            "explanation": [
                ['abcc', 'abca', 'bcab', '', ''],
                ['bcc', 'abca', 'bcab', 'a', ''],
                ['cc', 'abca', 'bcab', 'a', 'b'],
                ['cc', 'bca', 'bcab', 'aa', 'b'],
                ['cc', 'ca', 'bcab', 'aa', 'bb'],
                ['ccc', 'a', 'bcab', 'aa', 'bb'],
                ['ccc', '', 'bcab', 'aaa', 'bb'],
                ['ccc', '', 'cab', 'aaa', 'bbb'],
                ['cccc', '', 'ab', 'aaa', 'bbb'],
                ['cccc', '', 'b', 'aaaa', 'bbb'],
                ['cccc', '', '', 'aaaa', 'bbbb']],
        },
        {
            "input": [["abca", "bcbc", "aabc", "", ""]],
            "answer": 10,
            "explanation": [
                ['abca', 'bcbc', 'aabc', '', ''],
                ['bca', 'bcbc', 'aabc', 'a', ''],
                ['ca', 'bcbc', 'aabc', 'a', 'b'],
                ['ca', 'cbc', 'aabc', 'a', 'bb'],
                ['a', 'ccbc', 'aabc', 'a', 'bb'],
                ['', 'ccbc', 'aabc', 'aa', 'bb'],
                ['', 'ccbc', 'bc', 'aaaa', 'bb'],
                ['', 'ccbc', 'c', 'aaaa', 'bbb'],
                ['', 'bc', 'ccc', 'aaaa', 'bbb'],
                ['', 'c', 'ccc', 'aaaa', 'bbbb'],
                ['', '', 'cccc', 'aaaa', 'bbbb']],
        },
    ],
    "Extra": [
        {
            "input": [["abac", "daeb", "beba", "ddde", "eccc", "", ""]],
            "answer": 12,
            "explanation": [
                ['abac', 'daeb', 'beba', 'ddde', 'eccc', '', ''],
                ['abac', 'aeb', 'beba', 'ddde', 'eccc', 'd', ''],
                ['bac', 'aaeb', 'beba', 'ddde', 'eccc', 'd', ''],
                ['bbac', 'aaeb', 'eba', 'ddde', 'eccc', 'd', ''],
                ['bbac', 'aaeb', 'eba', 'e', 'eccc', 'dddd', ''],
                ['bbac', 'aaeb', 'ba', 'ee', 'eccc', 'dddd', ''],
                ['ac', 'aaeb', 'bbba', 'ee', 'eccc', 'dddd', ''],
                ['aaac', 'eb', 'bbba', 'ee', 'eccc', 'dddd', ''],
                ['aaac', 'b', 'bbba', 'eee', 'eccc', 'dddd', ''],
                ['aaac', 'bbbb', 'a', 'eee', 'eccc', 'dddd', ''],
                ['c', 'bbbb', 'aaaa', 'eee', 'eccc', 'dddd', ''],
                ['c', 'bbbb', 'aaaa', 'eeee', 'ccc', 'dddd', ''],
                ['', 'bbbb', 'aaaa', 'eeee', 'cccc', 'dddd', '']],
        },
        {
            "input": [["abcc", "abad", "cbed", "acee", "edbd", "", ""]],
            "answer": 15,
            "explanation": [
                ['abcc', 'abad', 'cbed', 'acee', 'edbd', '', ''],
                ['bcc', 'abad', 'cbed', 'acee', 'edbd', 'a', ''],
                ['cc', 'abad', 'cbed', 'acee', 'edbd', 'a', 'b'],
                ['cc', 'bad', 'cbed', 'acee', 'edbd', 'aa', 'b'],
                ['cc', 'ad', 'cbed', 'acee', 'edbd', 'aa', 'bb'],
                ['cc', 'd', 'cbed', 'acee', 'edbd', 'aaa', 'bb'],
                ['ccc', 'd', 'bed', 'acee', 'edbd', 'aaa', 'bb'],
                ['ccc', 'd', 'ed', 'acee', 'edbd', 'aaa', 'bbb'],
                ['ccc', 'd', 'ed', 'cee', 'edbd', 'aaaa', 'bbb'],
                ['cccc', 'd', 'ed', 'ee', 'edbd', 'aaaa', 'bbb'],
                ['cccc', 'd', 'd', 'eee', 'edbd', 'aaaa', 'bbb'],
                ['cccc', '', 'dd', 'eee', 'edbd', 'aaaa', 'bbb'],
                ['cccc', '', 'dd', 'eeee', 'dbd', 'aaaa', 'bbb'],
                ['cccc', '', 'ddd', 'eeee', 'bd', 'aaaa', 'bbb'],
                ['cccc', '', 'ddd', 'eeee', 'd', 'aaaa', 'bbbb'],
                ['cccc', '', '', 'eeee', 'dddd', 'aaaa', 'bbbb']],
        },
        {
            "input": [["abbc", "bddc", "aeca", "eebd", "edca", "", ""]],
            "answer": 14,
            "explanation": [
                ['abbc', 'bddc', 'aeca', 'eebd', 'edca', '', ''],
                ['abbc', 'ddc', 'aeca', 'eebd', 'edca', 'b', ''],
                ['abbc', 'ddc', 'aeca', 'bd', 'edca', 'b', 'ee'],
                ['abbc', 'ddc', 'aeca', 'd', 'edca', 'bb', 'ee'],
                ['abbc', 'c', 'aeca', 'ddd', 'edca', 'bb', 'ee'],
                ['abbc', 'c', 'aeca', 'ddd', 'dca', 'bb', 'eee'],
                ['abbc', 'c', 'aeca', 'dddd', 'ca', 'bb', 'eee'],
                ['abbc', 'cc', 'aeca', 'dddd', 'a', 'bb', 'eee'],
                ['bbc', 'cc', 'aeca', 'dddd', 'aa', 'bb', 'eee'],
                ['c', 'cc', 'aeca', 'dddd', 'aa', 'bbbb', 'eee'],
                ['', 'ccc', 'aeca', 'dddd', 'aa', 'bbbb', 'eee'],
                ['', 'ccc', 'eca', 'dddd', 'aaa', 'bbbb', 'eee'],
                ['', 'ccc', 'ca', 'dddd', 'aaa', 'bbbb', 'eeee'],
                ['', 'cccc', 'a', 'dddd', 'aaa', 'bbbb', 'eeee'],
                ['', 'cccc', '', 'dddd', 'aaaa', 'bbbb', 'eeee']],
        },
        {
            "input": [["abcd", "dedc", "aaed", "ebcb", "ebac", "", ""]],
            "answer": 16,
            "explanation": [
                ['abcd', 'dedc', 'aaed', 'ebcb', 'ebac', '', ''],
                ['bcd', 'dedc', 'aaed', 'ebcb', 'ebac', 'a', ''],
                ['bcd', 'dedc', 'ed', 'ebcb', 'ebac', 'aaa', ''],
                ['bcd', 'dedc', 'd', 'ebcb', 'ebac', 'aaa', 'e'],
                ['bcd', 'edc', 'dd', 'ebcb', 'ebac', 'aaa', 'e'],
                ['bcd', 'dc', 'dd', 'ebcb', 'ebac', 'aaa', 'ee'],
                ['bcd', 'c', 'ddd', 'ebcb', 'ebac', 'aaa', 'ee'],
                ['bcd', 'c', 'ddd', 'bcb', 'ebac', 'aaa', 'eee'],
                ['bbcd', 'c', 'ddd', 'cb', 'ebac', 'aaa', 'eee'],
                ['bbcd', 'cc', 'ddd', 'b', 'ebac', 'aaa', 'eee'],
                ['cd', 'cc', 'ddd', 'bbb', 'ebac', 'aaa', 'eee'],
                ['d', 'ccc', 'ddd', 'bbb', 'ebac', 'aaa', 'eee'],
                ['', 'ccc', 'dddd', 'bbb', 'ebac', 'aaa', 'eee'],
                ['', 'ccc', 'dddd', 'bbb', 'bac', 'aaa', 'eeee'],
                ['', 'ccc', 'dddd', 'bbbb', 'ac', 'aaa', 'eeee'],
                ['', 'ccc', 'dddd', 'bbbb', 'c', 'aaaa', 'eeee'],
                ['', '', 'dddd', 'bbbb', 'cccc', 'aaaa', 'eeee']],
        },
        {
            "input": [["abbc", "daee", "cacf", "aggf", "dfeg", "bbdc", "egfd", "", ""]],
            "answer": 19,
            "explanation": [
                ['abbc', 'daee', 'cacf', 'aggf', 'dfeg', 'bbdc', 'egfd', '', ''],
                ['bbc', 'daee', 'cacf', 'aggf', 'dfeg', 'bbdc', 'egfd', 'a', ''],
                ['c', 'daee', 'cacf', 'aggf', 'dfeg', 'bbdc', 'egfd', 'a', 'bb'],
                ['cc', 'daee', 'acf', 'aggf', 'dfeg', 'bbdc', 'egfd', 'a', 'bb'],
                ['cc', 'daee', 'cf', 'aggf', 'dfeg', 'bbdc', 'egfd', 'aa', 'bb'],
                ['', 'daee', 'cccf', 'aggf', 'dfeg', 'bbdc', 'egfd', 'aa', 'bb'],
                ['', 'daee', 'cccf', 'ggf', 'dfeg', 'bbdc', 'egfd', 'aaa', 'bb'],
                ['', 'daee', 'cccf', 'ggf', 'dfeg', 'dc', 'egfd', 'aaa', 'bbbb'],
                ['', 'aee', 'cccf', 'ggf', 'dfeg', 'ddc', 'egfd', 'aaa', 'bbbb'],
                ['', 'ee', 'cccf', 'ggf', 'dfeg', 'ddc', 'egfd', 'aaaa', 'bbbb'],
                ['', 'ee', 'cccf', 'ggf', 'feg', 'dddc', 'egfd', 'aaaa', 'bbbb'],
                ['', 'eee', 'cccf', 'ggf', 'feg', 'dddc', 'gfd', 'aaaa', 'bbbb'],
                ['', 'eee', 'cccf', 'gggf', 'feg', 'dddc', 'fd', 'aaaa', 'bbbb'],
                ['', 'eee', 'cccf', 'gggf', 'eg', 'dddc', 'ffd', 'aaaa', 'bbbb'],
                ['', 'eeee', 'cccf', 'gggf', 'g', 'dddc', 'ffd', 'aaaa', 'bbbb'],
                ['', 'eeee', 'cccf', 'f', 'gggg', 'dddc', 'ffd', 'aaaa', 'bbbb'],
                ['', 'eeee', 'cccf', 'fff', 'gggg', 'dddc', 'd', 'aaaa', 'bbbb'],
                ['', 'eeee', 'cccf', 'fff', 'gggg', 'c', 'dddd', 'aaaa', 'bbbb'],
                ['', 'eeee', 'f', 'fff', 'gggg', 'cccc', 'dddd', 'aaaa', 'bbbb'],
                ['', 'eeee', '', 'ffff', 'gggg', 'cccc', 'dddd', 'aaaa', 'bbbb']],
        },
        {
            "input": [["abbcac", "acccdb", "ebdeee", "eaabac", "ddbedd", "", ""]],
            "answer": 19,
            "explanation": [
                ['abbcac', 'acccdb', 'ebdeee', 'eaabac', 'ddbedd', '', ''],
                ['bbcac', 'acccdb', 'ebdeee', 'eaabac', 'ddbedd', 'a', ''],
                ['cac', 'acccdb', 'ebdeee', 'eaabac', 'ddbedd', 'a', 'bb'],
                ['cac', 'cccdb', 'ebdeee', 'eaabac', 'ddbedd', 'aa', 'bb'],
                ['ac', 'ccccdb', 'ebdeee', 'eaabac', 'ddbedd', 'aa', 'bb'],
                ['c', 'ccccdb', 'ebdeee', 'eaabac', 'ddbedd', 'aaa', 'bb'],
                ['ccccc', 'db', 'ebdeee', 'eaabac', 'ddbedd', 'aaa', 'bb'],
                ['ccccc', 'dddb', 'ebdeee', 'eaabac', 'bedd', 'aaa', 'bb'],
                ['ccccc', 'dddb', 'ebdeee', 'eaabac', 'edd', 'aaa', 'bbb'],
                ['ccccc', 'dddb', 'bdeee', 'eaabac', 'eedd', 'aaa', 'bbb'],
                ['ccccc', 'dddb', 'deee', 'eaabac', 'eedd', 'aaa', 'bbbb'],
                ['ccccc', 'ddddb', 'eee', 'eaabac', 'eedd', 'aaa', 'bbbb'],
                ['ccccc', 'ddddb', 'eeee', 'aabac', 'eedd', 'aaa', 'bbbb'],
                ['ccccc', 'ddddb', 'eeee', 'bac', 'eedd', 'aaaaa', 'bbbb'],
                ['ccccc', 'ddddb', 'eeee', 'ac', 'eedd', 'aaaaa', 'bbbbb'],
                ['ccccc', 'ddddb', 'eeee', 'c', 'eedd', 'aaaaaa', 'bbbbb'],
                ['', 'ddddb', 'eeee', 'cccccc', 'eedd', 'aaaaaa', 'bbbbb'],
                ['', 'ddddb', 'eeeeee', 'cccccc', 'dd', 'aaaaaa', 'bbbbb'],
                ['', 'b', 'eeeeee', 'cccccc', 'dddddd', 'aaaaaa', 'bbbbb'],
                ['', '', 'eeeeee', 'cccccc', 'dddddd', 'aaaaaa', 'bbbbbb']],
        },
        {
            "input": [["abacdaab", "accdbadc", "dddbbcbd", "bbcadcac", "", ""]],
            "answer": 24,
            "explanation": [
                ['abacdaab', 'accdbadc', 'dddbbcbd', 'bbcadcac', '', ''],
                ['bacdaab', 'accdbadc', 'dddbbcbd', 'bbcadcac', 'a', ''],
                ['acdaab', 'accdbadc', 'dddbbcbd', 'bbcadcac', 'a', 'b'],
                ['cdaab', 'accdbadc', 'dddbbcbd', 'bbcadcac', 'aa', 'b'],
                ['cdaab', 'ccdbadc', 'dddbbcbd', 'bbcadcac', 'aaa', 'b'],
                ['daab', 'cccdbadc', 'dddbbcbd', 'bbcadcac', 'aaa', 'b'],
                ['ddddaab', 'cccdbadc', 'bbcbd', 'bbcadcac', 'aaa', 'b'],
                ['ddddaab', 'cccdbadc', 'cbd', 'bbcadcac', 'aaa', 'bbb'],
                ['ddddaab', 'dbadc', 'ccccbd', 'bbcadcac', 'aaa', 'bbb'],
                ['dddddaab', 'badc', 'ccccbd', 'bbcadcac', 'aaa', 'bbb'],
                ['dddddaab', 'adc', 'ccccbd', 'bbcadcac', 'aaa', 'bbbb'],
                ['dddddaab', 'dc', 'ccccbd', 'bbcadcac', 'aaaa', 'bbbb'],
                ['aab', 'ddddddc', 'ccccbd', 'bbcadcac', 'aaaa', 'bbbb'],
                ['b', 'ddddddc', 'ccccbd', 'bbcadcac', 'aaaaaa', 'bbbb'],
                ['', 'ddddddc', 'ccccbd', 'bbcadcac', 'aaaaaa', 'bbbbb'],
                ['', 'ddddddc', 'ccccbd', 'cadcac', 'aaaaaa', 'bbbbbbb'],
                ['', 'ddddddc', 'cccccbd', 'adcac', 'aaaaaa', 'bbbbbbb'],
                ['', 'ddddddc', 'cccccbd', 'dcac', 'aaaaaaa', 'bbbbbbb'],
                ['', 'dddddddc', 'cccccbd', 'cac', 'aaaaaaa', 'bbbbbbb'],
                ['', 'dddddddc', 'bd', 'ccccccac', 'aaaaaaa', 'bbbbbbb'],
                ['', 'dddddddc', 'd', 'ccccccac', 'aaaaaaa', 'bbbbbbbb'],
                ['', 'c', 'dddddddd', 'ccccccac', 'aaaaaaa', 'bbbbbbbb'],
                ['', 'ccccccc', 'dddddddd', 'ac', 'aaaaaaa', 'bbbbbbbb'],
                ['', 'ccccccc', 'dddddddd', 'c', 'aaaaaaaa', 'bbbbbbbb'],
                ['', '', 'dddddddd', 'cccccccc', 'aaaaaaaa', 'bbbbbbbb']],
        },
    ]
}
